site_name: Desarrollo de aplicaciones web en entorno servidor.
site_url: https://fjagui.github.io/web-dawes/
repo_url: https://github.com/fjagui/web-dawes/
repo_name: web-dawes
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - toc:
      permalink: true   
      toc_depth: 3
  - attr_list

nav:
  - Inicio: index.md
  - Unidad 1: 
      - Teoría: UD1/index.md
      - Actividades: UD1/practicas.md
      - RA y CE: UD1/ra.md
#   - Unidad 2: 
#       - Teoría: UD2/index.md
#       - Actividades: UD2/practicas.md
#       - RA y CE: UD2/ra.md
#   - Unidad 3: 
#       - Teoría: UD3/index.md
#       - Actividades: UD3/practicas.md
#       - RA y CE: UD3/ra.md
#   - Unidad 4: 
#       - Teoría: UD4/index.md
#       - Actividades: UD4/practicas.md
#       - RA y CE: UD4/ra.md
#   - Unidad 5: 
#       - Teoría: UD5/index.md
#       - Actividades: UD5/practicas.md
#       - RA y CE: UD5/ra.md
#   - Unidad 6: 
#       - Teoría: UD6/index.md
#       - Actividades: UD6/practicas.md
#       - RA y CE: UD6/ra.md
